// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntxkzloqhwbiuwytluel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eGt6bG9xaHdiaXV3eXRsdWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTQ2MjgsImV4cCI6MjA2MzczMDYyOH0.qzZqyUUNVoSQKWAKMT_SwRwM5j1AGVJwLGkWBNcgYYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);